group_finder/urls.py
from django.urls import path

from . import views

app_name = 'group_finder'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('account/', views.AccountView.as_view(), name='account'),
    path('account/update/', views.edit_profile, name='account_update'),
    path('about/', views.about, name='about'),
    path('<int:pk>/join/', views.GameApply.as_view(), name='game_apply'),
    path('create/', views.GameCreate.as_view(), name='game_create'),
    path('<int:pk>/update/', views.GameUpdate.as_view(), name='game_update'),
    path('<int:pk>/delete/', views.GameDelete.as_view(), name='game_delete'),
    path('accounts/signup/', views.signup, name='signup'),
    path('<int:pk>/character/', views.CharCreate.as_view(), name='character_create'),
    # path('<int:pk>/character/update', views.CharUpdate.as_view(), name='character_update'),
    path('<int:pk>/approve/<user_id_string>', views.Approve.as_view(), name='approve'),
    path('<int:pk>/deny/<user_id_string>', views.Deny.as_view(), name='deny'),
]

p3dd/urls.py
from django.contrib import admin
from django.urls import include, path
from group_finder import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.IndexView.as_view(), name='index'),
    path('', views.app_redirect, name='redirect'),
    path('group_finder/', include('group_finder.urls')),
    path('group_finder/accounts/', include('django.contrib.auth.urls')),
]

group_finder/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.postgres.fields import ArrayField

from django.db.models.signals import post_save
from django.dispatch import receiver


class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    notification = models.CharField(max_length=200, default='None')


class Game(models.Model):
    users = models.ManyToManyField(User)
    game_text = models.CharField(max_length=200, verbose_name=('Game Name'))
    campaign_text = models.CharField(max_length=200, verbose_name=('Campaign Name'))
    game_type = models.CharField(max_length=100, verbose_name=('Game'))
    format_edition = models.CharField(max_length=50, verbose_name=('Format'))
    creation_date = models.DateTimeField(('date created'), default=timezone.now)
    host_id = models.IntegerField()
    accepting_players = models.BooleanField(blank=False, default=True)
    applications = ArrayField(ArrayField(models.CharField(max_length=50), default=list), default=list, null=True)
    def __str__(self):
        return self.game_text
    def get_absolute_url(self):
        return reverse('group_finder:detail', kwargs={'pk': self.pk})


class Character(models.Model):
    name_text = models.CharField(max_length=50, verbose_name=('Character Name'))
    player_text = models.CharField(max_length=30, verbose_name=('Your Name'))
    race_text = models.CharField(max_length=30, verbose_name=('Character Race'))
    class_text = models.CharField(max_length=30, verbose_name=('Character Class'))
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    def __str__(self):
        return self.name_text
    def get_absolute_url(self):
        return reverse('group_finder:detail', kwargs={'pk': self.game.id})


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Account.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.account.save()

group_finder/forms.py
from django import forms
from .models import Game, Character
from django.contrib.auth.models import User


GAME_TYPE_CHOICES = [
    ('', ''),
    ('Dungeons and Dragons', 'D&D'), 
    ('Magic the Gathering', 'Magic the Gathering'),
    ('Board Games', 'Board Games'),
    ('Yu-Gi-Oh TCG', 'Yu-Gi-Oh TCG'),
    ('Pokemon TCG', 'Pokemon TCG'),
    ('Pathfinder', 'Pathfinder'),
    ('Warhammer', 'Warhammer'),
    ('Other', 'Other')
]

class CreateGameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = [
            'game_text',
            'campaign_text',
            'game_type'
        ]
        widgets = {
            'game_type': forms.Select(choices=GAME_TYPE_CHOICES)
        }

class UpdateGameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = [
            'game_text',
            'campaign_text',
            'game_type',
            'accepting_players'
        ]
        widgets = {
            'game_type': forms.Select(choices=GAME_TYPE_CHOICES)
        }


class ChangeUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'email'
        ]
        
    def __init__(self, *args, **kwargs):
        super(ChangeUserForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].label = 'Display Name'
        f = self.fields.get('user_permissions', None)
        if f is not None:
            f.queryset = f.queryset.select_related('content_type')


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_object = self.request.user
        context["first_name"] = user_object.first_name        
        return context
    def clean_password(self):
        return self.initial["password"]

group_finder/views.py
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.views import generic, View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils import timezone
# from django.template import loader
from django.db.models import Count
from django.urls import reverse_lazy, reverse

from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import login
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from .models import Game, Character, Account
from .forms import CreateGameForm,UpdateGameForm,ChangeUserForm

from django.core.mail import send_mail

# import django.dispatch
# from django.core.signals import request_finished
# from django.dispatch import receiver
# apply_signal = django.dispatch.Signal(providing_args=['game_id', 'user_object'])

# from django.template import Context, Template



def app_redirect(self):
    return redirect(reverse('group_finder:index'))

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=32,label = "Display Name", required=True)
    email = forms.EmailField(label = "Email", required=True)
    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')
    
    def save(self, commit=True):
        user = super(SignUpForm, self).save(commit=False)
        user.display_name = self.cleaned_data['first_name']
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user 

#need to build in a more dynamic error message
def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            if user.email and User.objects.filter(email=user.email).exclude(username=user.username).exists():
                context = {'form': form, 'error_message': 'This email address has already been used'}
                user.delete()
                return render(request, 'registration/signup.html', context)
            login(request, user)
            return redirect('/group_finder/')
        else:
            error_message = "Invalid Signup: either your username has been taken or your passwords did not fulfill the requirement"
    form = SignUpForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

def about(request):
    return render(request, 'group_finder/about.html')

class IndexView(generic.ListView):
    template_name = 'group_finder/index.html'
    context_object_name = 'latest_game_list'
    def get_queryset(self):

        if self.request.GET:

            form = self.request.GET

            games = Game.objects.all().annotate(num_players=(Count('users')))

            if form.get('searchGame', ''):
                games = games.filter(game_text__icontains=(form.get('searchGame', '')))
            if form.get('searchCampaign', ''):
                games = games.filter(campaign_text__icontains=(form.get('searchCampaign', '')))
            
            if form.get('newPlayers') == 'on':
                games = games.filter(accepting_players=True)

            if form.get('chooseGame', ''):
                games = games.filter(game_type=(form.get('chooseGame')))

            sort = form.get('sortBy', 'recent')
            
            if sort == 'recent':
                games = games.order_by('-creation_date')
            elif sort == 'name':
                games = games.order_by('game_text')
            elif sort == 'numPlayersAscending':
                games = games.order_by('num_players')
            elif sort == 'numPlayersDescending':
                games = games.order_by('-num_players')
    
        else:

            games = Game.objects.all().annotate(num_players=(Count('users'))).order_by('-creation_date')

        return games

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        if not self.request.GET:
            if self.request.user.id: 
                if self.request.user.account:
                    if self.request.user.account.notification != 'None':
                        context["notification"] = self.request.user.account.notification

        return context

class DetailView(generic.DetailView):
    model = Game
    template_name = 'group_finder/detail.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_participants = self.object.users
        participant_names = []
        in_game = False
        for participant in current_participants.all():
            if participant.id == self.request.user.id:
                participant_names.append(str(participant) + '(You)')
                in_game = True
            else:
                participant_names.append(str(participant))
        
        context["in_game"] = in_game

        host_object = User.objects.get(id=self.object.host_id)
        if host_object.id == self.request.user.id:
            context["host"] = str(host_object) + '(You)'
        else:
            context["host"] = str(host_object)

        if self.object.game_type == 'Dungeons and Dragons' or self.object.game_type == 'Pathfinder':
            context["character"] = True
        else:
            context["character"] = False

        context["participant_names"] = participant_names
        num_players = len(participant_names)
        context["num_players"] = num_players
        if num_players >= 1:
            context["last_participant"] = participant_names[num_players - 1]
        elif num_players == 1:
            context["last_participant"] = participant_names[0]
        
        # characters = self.object.character_set.all()
        context["characters"] = self.object.character_set.all()
        return context

class AccountView(LoginRequiredMixin, generic.ListView):
    template_name = 'group_finder/account.html'
    context_object_name = 'personal_game_list'

    def get_queryset(self):

        user_game = Game.objects.filter(users__pk=self.request.user.id)

        user_game.order_by('-creation_date')

        for game in user_game:
            game.host = str(User.objects.get(id = game.host_id))
            if self.request.user.id == game.host_id:
                game.host += ' (You)'

        for game in user_game:
            if game.host_id == self.request.user.id:
                if len(game.applications) > 0:
                    game.application_username = []
                    for application in game.applications:
                        game.application_username.append(f'{application[0]} userid:{application[1]}')

        return user_game

        # ALSO COULD DISPLAY YOUR CHARACTER THAT YOU'RE PLAYING IN THIS GAME

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_object = self.request.user
        
        context["username"] = user_object.username
        context["email"] = user_object.email
        context["first_name"] = user_object.first_name
        # context["last_name"] = user_object.last_name
        context["date_joined"] = user_object.date_joined
        
        return context


@login_required
def edit_profile(request):
    if request.method == "POST":
        form = ChangeUserForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('group_finder:account'))
    else:
        form = ChangeUserForm(instance=request.user)
        
        args = {'form':form}
        return render(request, 'group_finder/account_form.html', args)


class ManagementView(LoginRequiredMixin, generic.ListView):
    template_name = 'group_finder/management.html'
    context_object_name = 'hosted_game_list'

    def get_queryset(self):
        """
        Return your created games.
        """
        hosted_games = Game.objects.filter(users=self.request.user).filter(host_id=self.request.user.id).order_by('-creation_date')

        for game in hosted_games:
            if len(game.applications) > 0:
                game.application_username = []
                for application in game.applications:
                    game.application_username.append(application[0])

        # CURRENT USER/ACCOUNT'S CREATED GAMES
        return hosted_games

class GameCreate(LoginRequiredMixin, CreateView):
    form_class = CreateGameForm
    model = Game
    
    def form_valid(self,form):
        form.instance.host_id = self.request.user.id
        self.object = form.save()
        self.object.users.add(User.objects.get(id=self.request.user.id))
        messages.success(self.request,"The game post is created successfully!")
        return super().form_valid(form)

class GameUpdate(LoginRequiredMixin, SuccessMessageMixin,UpdateView):
    success_message = "The game post is updated!"
    form_class = UpdateGameForm
    model = Game

class CharCreate(LoginRequiredMixin, CreateView):
    # form_class = CreateCharForm
    model = Character
    fields = ['name_text', 'player_text', 'race_text', 'class_text']

    def form_valid(self, form):
        form.instance.game = Game.objects.get(id=self.kwargs['pk'])
        messages.success(self.request,"The character is created successfully!")
        return super().form_valid(form)

# class CharUpdate(LoginRequiredMixin, UpdateView):
#     model = Character
#     fields = ['name_text', 'player_text', 'race_text', 'class_text']

#     def form_valid(self, form):
#         form.instance.game = Game.objects.get(id=self.kwargs['pk'])

group_finder/templates/group_finder/about.html
{% extends 'base.html' %}
{% block content %}
<div id="aboutContainer">
    <h2>About</h2>
    <h3>Looking For Party <br> A web app deicated to helping you find playgroups for your favorite games and hobbies... <br> It's free and easy to use!</h3>
</div>
{% endblock %}

group_finder/templates/group_finder/account.html
{% extends 'base.html' %}
{% block content %}
<div class="accountInfo">
    <h2>This is your account info</h2>
    <p><span class="greyed">Username:</span> {{ username }}</p>
    <p><span class="greyed">Display Name:</span> {{ first_name }}</p>
    <p><span class="greyed">Email Address:</span> {{ email }}</p>
    <p><span class="greyed">Date Joined:</span> {{ date_joined }}</p>
    <a href="{% url 'group_finder:account_update'%}"><button>Edit</button></a>

</div>
<div class="gamesIn">
    {% if personal_game_list%}
        <h2>These are the games you're in</h2>
        {% for game in personal_game_list %}
    

        <p><span class="greyed">Game Name:</span><a href="{% url 'group_finder:detail' game.id %}"> {{ game.game_text }}</a></p>
        <p><span class="greyed">Host:</span> {{ game.host }}</p>
        
        {% if game.application_username %}

        <p>Applications:</p>

        {% for username in game.application_username %}
        
        <p>{{ username }} <a href="{% url 'group_finder:approve' game.id username %}"><button>Approve</button></a> <a href="{% url 'group_finder:deny' pk=game.id user_id_string=username %}"><button>Deny</button></a> </p>

        {% endfor %}

        {% endif %}

        {% endfor %}
    {% else %}
        <h2>There are no games you're in! Join or start a game!</h2>
    {% endif %}

</div>
{% endblock %}

group_finder/templates/group_finder/account_form.html
{% extends 'base.html' %}
{% block content %}

<div>
    <h2>Edit {{user.username}}</h2>

    <form action="" method="POST">
        {% csrf_token%}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit" value="Submit!">
    </form>

</div>
{% endblock %}

group_finder/templates/group_finder/character_form.html
{% extends 'base.html' %}
{% block content %}

<div>
    {% if object %}
        <h2>Edit{{object.name}}</h2>
    {% else %}
        <h2>Create a New Character</h2>
    {% endif %}

    <form action="" method="POST">
        {% csrf_token%}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit" value="Submit!">
    </form>
</div>

{% endblock %}

group_finder/templates/group_finder/detail.html
{% extends 'base.html' %}
{% block content %}
<div id="gameDetail">
    <h2>{{ object.game_text }}</h2>
    <div>
        <p><span class="greyed">Game:</span> {{ object.game_type }}</p>
        <p><span class="greyed">Campaign:</span> {{ object.campaign_text }}</p>
        <p><span class="greyed">Host:</span> {{ host }}</p>
        <p><span class="greyed">Number of Players:</span> {{ num_players }}</p>
        <p><span class="greyed">Current Members:</span>
            {% for participant in participant_names %}
            {% if participant == last_participant %}
            {{ participant }}
            {% else %}
            {{ participant }},
            {% endif %}        
            {% endfor %}
        </p>
        <div>
            <p><span class="greyed">Accepting New Players?</span>             
            {% if object.accepting_players %}
                &nbsp; <span class="green">Yes</span>
        
            {% else %}
                &nbsp; <span class="red">No</span>
            {% endif %}
            </p>

        {% if character and in_game %}
        
        <div class="joinButtons">
            <div id="charList">
                <h2>Characters in this game: </h2>
                    <button><a href="{% url 'group_finder:character_create' object.id %}">Create a new character for this game</a></button>
                    <ul>
                    {% for character in characters %}
                        <li>
                            <p>Character Name:<span class="blacken">{{ character.name_text }}</span></p>
                            <p>Player Name: <span class="blacken">{{ character.player_text }}</span></p>
                            <p>Character Race: <span class="blacken">{{ character.race_text }}</span></p>
                            <p>Character Class: <span class="blacken">{{ character.class_text }}</span></p>
                        </li>
                    {% endfor %}
                    </ul>

                
                
            </div>
        </div>
            
        {% endif %}

            {% if object and object.host_id == request.user.id %}</h2>
                <div class="edButton">
                    <a href="{% url 'group_finder:game_update' game.id %}">Edit</a>
                </div>
                <div class="edButton">
                    <a href="{% url 'group_finder:game_delete' game.id %}">Delete</a>
                </div>

            {% elif object and object.host_id != request.user.id %}

            <div>
                <form action="{% url 'group_finder:game_apply' game.id %}" method="GET">
                    <input type="submit" value="Apply to Join This Game">

                    {% if character %}

                    <label for="role">Specify Role</label>
                    <select name="role" id="role">
                        <option value="any">Any/I don't care</option>
                        <option value="tank">Tank</option>
                        <option value="healer">Healer</option>
                        <option value="melee_dps">Melee DPS</option>
                        <option value="ranged_dps">Ranged DPS</option>
                        <option value="utility">Utility</option>
                    </select>

                    {% endif %}

                </form>
            </div>

        {% endif %}

    </div>

</div>
{% endblock %}

group_finder/templates/group_finder/game_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <div class="delete">
    <h1>Delete</h1>

    <h4>Are you sure you want to delete {{ object.name }}?</h4>

    <form action="" method="POST">
      {% csrf_token %}
      <input type="submit" value="Yes Delete!">
      <div class="deleteCancel">
        <a href="{% url 'group_finder:detail' game.id %}">Cancel</a>
      </div>
    </form>
  </div>
{% endblock %}

group_finder/templates/group_finder/game_form.html
{% extends 'base.html' %}
{% block content %}

<div>
    {% if object %}
        <h2>Edit{{object.name}}</h2>
    {% else %}
        <h2>Create a New Game</h2>
    {% endif %}
    <form action="" method="POST">
        {% csrf_token%}
        <table>
            {{form.as_table}}
        </table>

        {% if object and object.host_id == request.user.id %}

        {% if object.game_type == 'Magic the Gathering' %}
        <label for="magic_format">Specify Format</label>
        <select name="format_edition" id="magic_format">
            <option value="Unspecified"></option>
            <option value="Standard">Standard</option>
            <option value="Modern">Modern</option>
            <option value="Commander">Commander</option>
            <option value="Legacy">Legacy</option>
            <option value="Limited">Limited</option>
            <option value="Legacy">Legacy</option>
            <option value="Pauper">Pauper</option>
        </select>
        {% endif %}

        {% if object.game_type == 'Dungeons and Dragons' %}
        <label for="dnd_format">Specify Edition</label>
        <select name="format_edition" id="dnd_format">
            <option value="Unspecified"></option>
            <option value="5e">5e</option>
            <option value="4e">4e</option>
            <option value="3.5e">3.5e</option>
            <option value="AD&D">AD&D</option>
        </select>
        {% endif %}

        {% if object.game_type == 'Yu-Gi-Oh' %}
        <label for="yugioh_format">Specify Format</label>
        <select name="format_edition" id="yugioh_format">
            <option value="Unspecified"></option>
            <option value="MR5">MR5</option>
            <option value="MR4">MR4</option>
            <option value="MR3">MR3</option>
            <option value="MR2">MR2</option>
            <option value="MR1">MR1</option>
            <option value="Legacy">Legacy</option>
        </select>
        {% endif %}

        <div class="deleteCancel2">
            <a href="{% url 'group_finder:game_delete' game.id %}">Delete</a>
        </div>
        {% endif %}
        <input type="submit" value="Submit!">
    </form>

</div>
{% endblock %}

group_finder/templates/group_finder/index.html
{% extends 'base.html' %}
{% block content %}

<div id="findGame">
    <h2>Find a Game</h2>
    <form action="/group_finder/" method="GET">
        {% csrf_token %}
        <div class="formContainer">
            <div>
                <label for="searchGame">Search by Game Name</label>
                <input type="text" id="searchGame" name="searchGame">
            </div>
            <div>
                <label for="sortBy">Sort By:</label>
                <select class="sortBy" name="sortBy" id="sortBy">
                    <option value="recent">Recently Created</option>
                    <option value="name">Game Name</option>
                    <option value="numPlayersDescending">Number of Players (descending)</option>
                    <option value="numPlayersAscending">Number of Players (ascending)</option>
                </select>
            </div>
        </div>
        <div class="formContainer">
            <div>
                <label for="searchCampaign">Search by Campaign Name</label>
                <input type="text" id="searchCampaign" name="searchCampaign">
            </div>
            <div>
                <label for="chooseGame">Filter By Game:</label>
                <select class="chooseGame" name="chooseGame" id="chooseGame">
                    <option value="">All</option>
                    <option value="Dungeons and Dragons">D&D</option>
                    <option value="Magic the Gathering">Magic the Gathering</option>
                    <option value="Board Games">Board Games</option>
                    <option value="Yu-Gi-Oh TCG">Yu-Gi-Oh TCG</option>
                    <option value="Pokemon TCG">Pokemon TCG</option>
                    <option value="Pathfinder">Pathfinder</option>
                    <option value="Warhammer">Warhammer</option>
                    <option value="Other">Other</option>
                </select>
            </div>
        </div>
        <div class="formContainer">
            <div>
                <label for="newPlayers">Only find games that are accepting new players</label>
                <input type="checkbox" id="newPlayers" name="newPlayers">
            </div>
            <input type="submit">
        </div>
    </form>
</div>

{% if notification %}

<div id="notification">
    <button>x</button>
    <p>Someone wants to join {{ notification }} --- <a href="{% url 'group_finder:account' %}">Go To</a></p>
</div>

{% endif %}

<div id="gameList">
    <h2>Recent Game Listings</h2>
    {% if latest_game_list %}
        <ul>
        {% for game in latest_game_list %}
        <li>
            <div class="center">
                <a href="{% url 'group_finder:detail' game.id %}">{{ game.game_text }}</a>
            </div>
            <p>Game: <span class="blacken">{{ game.game_type }}</span></p>
            <p>Campaign: <span class="blacken">{{ game.campaign_text }}</span></p>
            <p>Number of Players: <span class="blacken">{{ game.num_players }}</span></p>
            <p>Accepting New Players: 
                {% if game.accepting_players is True %}
                    <span class="green">{{ game.accepting_players }}</span></p>
                {% elif game.accepting_players is False %}
                    <span class="red">{{ game.accepting_players }}</span></p>
                {% endif %}
        </li>
        
        
        {% endfor %}
        </ul>
    {% else %}
        <p>No games are available.</p>
    {% endif %}
        
</div>
    
{% endblock %}